version: '3.1'

services:
  mariadb:
    container_name: postgres
    image: postgres:12.4-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks: 
  default:
    external: 
      name: ${DOCKER_NETWORK}